Feat: Added Folder/File structure for the video player section
thisisamank/desk pull request #7
Opened 2024-07-13 20:25 UTC by yash2324

<img width="1470" alt="Screenshot 2024-07-14 at 1 54 21 AM" src="https://github.com/user-attachments/assets/2de7796c-c44f-420a-bd94-53005022a86a">
<img width="1470" alt="Screenshot 2024-07-14 at 1 54 18 AM" src="https://github.com/user-attachments/assets/9c418bd6-3dcc-4990-a410-aee21d0d67c4">

2024-07-14 05:53 UTC, ishar19 requested changes

2024-07-14 05:53 UTC, ishar19 commented on desk-ui/src/app/components/FolderStructure.tsx
> +          `http://127.0.0.1:8000/course/:id?id=${course_id}`,
Have the url as an environment variable

2024-07-14 05:53 UTC, ishar19 commented on desk-ui/src/app/components/FolderStructure.tsx
> +          `http://127.0.0.1:8000/course/:id?id=${course_id}`,
Make a api folder to make all the calls, keep api calls seperate

2024-07-14 05:53 UTC, ishar19 commented on desk-ui/src/app/components/FolderStructure.tsx
> +        console.log(courseData);
Remove logs

2024-07-14 08:42 UTC, ishar19 reviewed
Does it also works when we have folder inside a folder?

2024-07-15 08:51 UTC, yash2324 commented
> Does it also works when we have folder inside a folder?

No it is not working for that just checked it displays that as a lecture 
Rest of the issues have been fixed

2024-07-21 07:34 UTC, ishar19 requested changes

2024-07-21 07:34 UTC, ishar19 commented on desk-ui/src/app/api/Folders/[id]/route.ts
> +    console.log(courseData);
remove success logs, only keep error logs

2024-07-21 07:34 UTC, ishar19 commented on server/app/api/controller/file_controller.py
> +def determine_file_type(file_name):
dont encapsulate file type, i need it for proper rendering

2024-07-21 10:09 UTC, yash2324 commented
@ishar19 bhaiya please check now

2024-07-21 10:42 UTC, ishar19 commented
Badiya, merge krra hu mai

2024-07-21 10:42 UTC, merged